"""Vision annotation and recognition support."""

from holdem_bot.vision.annotations import (
    AnnotatedButton,
    AnnotatedCard,
    AnnotatedSeat,
    AnnotatedText,
    ScreenRect,
    TableAnnotation,
)
from holdem_bot.vision.evaluate import evaluate_fixture, score_to_dict
from holdem_bot.vision.llm_annotation import (
    LlmAnnotationManifest,
    LlmFrameRequest,
    LlmRoiCrop,
    annotation_output_schema,
    build_llm_annotation_package,
    execute_llm_annotation_package,
)
from holdem_bot.vision.poker_legends_cards import (
    PokerLegendsCardPrediction,
    PokerLegendsCardTemplate,
    PokerLegendsCardTemplateManifest,
    PokerLegendsCardTemplateRecognizer,
    build_and_evaluate_poker_legends_card_templates,
    build_poker_legends_card_template_library,
    evaluate_poker_legends_card_templates,
)
from holdem_bot.vision.poker_legends_compare import (
    FieldComparison,
    PokerLegendsRoiButton,
    PokerLegendsRoiCard,
    PokerLegendsRoiOcrRecognizer,
    PokerLegendsRoiResult,
    PokerLegendsRoiText,
    build_poker_legends_recognition_comparison,
    compare_llm_candidate_to_roi,
)
from holdem_bot.vision.poker_legends_layout import (
    LayoutRegion,
    apply_poker_legends_layout,
    draw_layout_overlay,
    poker_legends_layout_regions,
)
from holdem_bot.vision.poker_legends_screen import (
    PokerLegendsRegionFeature,
    PokerLegendsScreenDetection,
    detect_poker_legends_screen_state,
    detect_poker_legends_screen_state_from_image,
    evaluate_poker_legends_screen_state,
)
from holdem_bot.vision.poker_legends_truth import (
    build_poker_legends_truth_overlay,
    merge_poker_legends_truth,
    screen_state_from_poker_legends_annotation,
)
from holdem_bot.vision.recognition import (
    CategoryScore,
    RecognitionScore,
    RecognizedButton,
    RecognizedCard,
    RecognizedSeat,
    RecognizedTable,
    evaluate_recognition,
    recognize_from_annotation,
)
from holdem_bot.vision.roi_ocr import RoiOcrConfig, RoiOcrRecognizer
from holdem_bot.vision.selection import (
    KeyframeSelectionManifest,
    KeyframeSelectionRequest,
    SelectedKeyframe,
    select_keyframes,
)
from holdem_bot.vision.video import (
    ExtractedFrame,
    VideoIngestManifest,
    VideoMetadata,
    ingest_video,
)

__all__ = [
    "AnnotatedButton",
    "AnnotatedCard",
    "AnnotatedSeat",
    "AnnotatedText",
    "CategoryScore",
    "ExtractedFrame",
    "FieldComparison",
    "KeyframeSelectionManifest",
    "KeyframeSelectionRequest",
    "LlmAnnotationManifest",
    "LlmFrameRequest",
    "LlmRoiCrop",
    "LayoutRegion",
    "PokerLegendsCardPrediction",
    "PokerLegendsCardTemplate",
    "PokerLegendsCardTemplateManifest",
    "PokerLegendsCardTemplateRecognizer",
    "PokerLegendsRoiButton",
    "PokerLegendsRoiCard",
    "PokerLegendsRoiOcrRecognizer",
    "PokerLegendsRoiResult",
    "PokerLegendsRoiText",
    "PokerLegendsRegionFeature",
    "PokerLegendsScreenDetection",
    "RecognitionScore",
    "RecognizedButton",
    "RecognizedCard",
    "RecognizedSeat",
    "RecognizedTable",
    "RoiOcrConfig",
    "RoiOcrRecognizer",
    "ScreenRect",
    "SelectedKeyframe",
    "TableAnnotation",
    "VideoIngestManifest",
    "VideoMetadata",
    "annotation_output_schema",
    "apply_poker_legends_layout",
    "build_llm_annotation_package",
    "build_and_evaluate_poker_legends_card_templates",
    "build_poker_legends_card_template_library",
    "build_poker_legends_recognition_comparison",
    "build_poker_legends_truth_overlay",
    "compare_llm_candidate_to_roi",
    "draw_layout_overlay",
    "detect_poker_legends_screen_state",
    "detect_poker_legends_screen_state_from_image",
    "evaluate_fixture",
    "evaluate_poker_legends_card_templates",
    "evaluate_poker_legends_screen_state",
    "evaluate_recognition",
    "execute_llm_annotation_package",
    "ingest_video",
    "merge_poker_legends_truth",
    "poker_legends_layout_regions",
    "recognize_from_annotation",
    "score_to_dict",
    "screen_state_from_poker_legends_annotation",
    "select_keyframes",
]
