"""Vision annotation and recognition support."""

from holdem_bot.vision.annotations import (
    AnnotatedButton,
    AnnotatedCard,
    AnnotatedSeat,
    AnnotatedText,
    ScreenRect,
    TableAnnotation,
)
from holdem_bot.vision.evaluate import evaluate_fixture, score_to_dict
from holdem_bot.vision.llm_annotation import (
    LlmAnnotationManifest,
    LlmFrameRequest,
    LlmRoiCrop,
    annotation_output_schema,
    build_llm_annotation_package,
    execute_llm_annotation_package,
)
from holdem_bot.vision.poker_legends_buttons import (
    PokerLegendsButtonPrediction,
    PokerLegendsButtonRecognizer,
    PokerLegendsButtonTemplate,
    PokerLegendsButtonTemplateManifest,
    build_and_evaluate_poker_legends_button_templates,
    build_poker_legends_button_template_library,
    evaluate_poker_legends_button_templates,
)
from holdem_bot.vision.poker_legends_card_classifier import (
    PokerLegendsCardClassifier,
    PokerLegendsCardClassifierManifest,
    PokerLegendsCardClassifierPrediction,
    PokerLegendsCardClassifierSample,
    build_and_evaluate_poker_legends_card_classifier,
    build_poker_legends_card_classifier,
    evaluate_poker_legends_card_classifier,
)
from holdem_bot.vision.poker_legends_card_consensus import (
    PokerLegendsCardConsensusPrediction,
    PokerLegendsCardConsensusRecognizer,
    evaluate_poker_legends_card_consensus,
    evaluate_poker_legends_card_consensus_suite,
)
from holdem_bot.vision.poker_legends_card_parts import (
    PokerLegendsCardPartPrediction,
    PokerLegendsCardPartTemplate,
    PokerLegendsCardPartTemplateManifest,
    PokerLegendsCardPartTemplateRecognizer,
    build_and_evaluate_poker_legends_card_part_templates,
    build_poker_legends_card_part_template_library,
    evaluate_poker_legends_card_part_templates,
)
from holdem_bot.vision.poker_legends_card_review import (
    PokerLegendsCardReviewCandidate,
    PokerLegendsCardReviewSelection,
    PokerLegendsCardReviewSource,
    PokerLegendsExcludedTruth,
    select_poker_legends_card_review_candidates,
)
from holdem_bot.vision.poker_legends_cards import (
    PokerLegendsCardPrediction,
    PokerLegendsCardTemplate,
    PokerLegendsCardTemplateManifest,
    PokerLegendsCardTemplateRecognizer,
    build_and_evaluate_poker_legends_card_templates,
    build_poker_legends_card_template_library,
    evaluate_poker_legends_card_templates,
)
from holdem_bot.vision.poker_legends_compare import (
    FieldComparison,
    PokerLegendsRoiButton,
    PokerLegendsRoiCard,
    PokerLegendsRoiOcrRecognizer,
    PokerLegendsRoiResult,
    PokerLegendsRoiText,
    build_poker_legends_recognition_comparison,
    compare_llm_candidate_to_roi,
)
from holdem_bot.vision.poker_legends_layout import (
    LayoutRegion,
    apply_poker_legends_layout,
    draw_layout_overlay,
    poker_legends_layout_regions,
)
from holdem_bot.vision.poker_legends_multi_templates import (
    PokerLegendsTemplateSource,
    build_and_evaluate_poker_legends_multi_templates,
    materialize_poker_legends_template_dataset,
)
from holdem_bot.vision.poker_legends_numbers import (
    PokerLegendsNumberPrediction,
    PokerLegendsNumberRecognizer,
    build_poker_legends_number_crop_dataset,
    build_poker_legends_number_ocr_report,
    parse_poker_legends_chip_amount,
    parse_poker_legends_chip_components,
    parse_poker_legends_chip_numbers,
)
from holdem_bot.vision.poker_legends_screen import (
    PokerLegendsRegionFeature,
    PokerLegendsScreenDetection,
    detect_poker_legends_screen_state,
    detect_poker_legends_screen_state_from_image,
    evaluate_poker_legends_screen_state,
)
from holdem_bot.vision.poker_legends_screen_scan import (
    PokerLegendsLlmCandidate,
    PokerLegendsScreenRun,
    PokerLegendsScreenScan,
    PokerLegendsScreenScanRow,
    build_poker_legends_screen_scan,
    scan_poker_legends_ingest,
)
from holdem_bot.vision.poker_legends_session import (
    PokerLegendsFrameObservation,
    PokerLegendsHandSegment,
    PokerLegendsSessionTimeline,
    PokerLegendsSessionTracker,
    PokerLegendsTimelineEvent,
    build_poker_legends_session_timeline,
)
from holdem_bot.vision.poker_legends_temporal import PokerLegendsTemporalTracker
from holdem_bot.vision.poker_legends_truth import (
    build_poker_legends_truth_overlay,
    merge_poker_legends_truth,
    screen_state_from_poker_legends_annotation,
)
from holdem_bot.vision.recognition import (
    CategoryScore,
    RecognitionScore,
    RecognizedButton,
    RecognizedCard,
    RecognizedSeat,
    RecognizedTable,
    evaluate_recognition,
    recognize_from_annotation,
)
from holdem_bot.vision.roi_ocr import RoiOcrConfig, RoiOcrRecognizer
from holdem_bot.vision.selection import (
    KeyframeSelectionManifest,
    KeyframeSelectionRequest,
    SelectedKeyframe,
    select_keyframes,
)
from holdem_bot.vision.video import (
    ExtractedFrame,
    VideoIngestManifest,
    VideoMetadata,
    ingest_video,
)

__all__ = [
    "AnnotatedButton",
    "AnnotatedCard",
    "AnnotatedSeat",
    "AnnotatedText",
    "CategoryScore",
    "ExtractedFrame",
    "FieldComparison",
    "KeyframeSelectionManifest",
    "KeyframeSelectionRequest",
    "LlmAnnotationManifest",
    "LlmFrameRequest",
    "LlmRoiCrop",
    "LayoutRegion",
    "PokerLegendsCardClassifier",
    "PokerLegendsCardClassifierManifest",
    "PokerLegendsCardClassifierPrediction",
    "PokerLegendsCardClassifierSample",
    "PokerLegendsCardConsensusPrediction",
    "PokerLegendsCardConsensusRecognizer",
    "PokerLegendsCardPrediction",
    "PokerLegendsCardPartPrediction",
    "PokerLegendsCardPartTemplate",
    "PokerLegendsCardPartTemplateManifest",
    "PokerLegendsCardPartTemplateRecognizer",
    "PokerLegendsCardReviewCandidate",
    "PokerLegendsCardReviewSelection",
    "PokerLegendsCardReviewSource",
    "PokerLegendsCardTemplate",
    "PokerLegendsCardTemplateManifest",
    "PokerLegendsCardTemplateRecognizer",
    "PokerLegendsButtonPrediction",
    "PokerLegendsButtonRecognizer",
    "PokerLegendsButtonTemplate",
    "PokerLegendsButtonTemplateManifest",
    "PokerLegendsExcludedTruth",
    "PokerLegendsRoiButton",
    "PokerLegendsRoiCard",
    "PokerLegendsRoiOcrRecognizer",
    "PokerLegendsRoiResult",
    "PokerLegendsRoiText",
    "PokerLegendsRegionFeature",
    "PokerLegendsScreenDetection",
    "PokerLegendsLlmCandidate",
    "PokerLegendsNumberPrediction",
    "PokerLegendsNumberRecognizer",
    "PokerLegendsScreenRun",
    "PokerLegendsScreenScan",
    "PokerLegendsScreenScanRow",
    "PokerLegendsFrameObservation",
    "PokerLegendsHandSegment",
    "PokerLegendsSessionTimeline",
    "PokerLegendsSessionTracker",
    "PokerLegendsTemporalTracker",
    "PokerLegendsTemplateSource",
    "PokerLegendsTimelineEvent",
    "RecognitionScore",
    "RecognizedButton",
    "RecognizedCard",
    "RecognizedSeat",
    "RecognizedTable",
    "RoiOcrConfig",
    "RoiOcrRecognizer",
    "ScreenRect",
    "SelectedKeyframe",
    "TableAnnotation",
    "VideoIngestManifest",
    "VideoMetadata",
    "annotation_output_schema",
    "apply_poker_legends_layout",
    "build_llm_annotation_package",
    "build_and_evaluate_poker_legends_card_classifier",
    "build_and_evaluate_poker_legends_card_part_templates",
    "build_and_evaluate_poker_legends_card_templates",
    "build_and_evaluate_poker_legends_button_templates",
    "build_poker_legends_card_classifier",
    "build_poker_legends_card_part_template_library",
    "build_poker_legends_card_template_library",
    "build_poker_legends_button_template_library",
    "build_and_evaluate_poker_legends_multi_templates",
    "build_poker_legends_recognition_comparison",
    "build_poker_legends_number_crop_dataset",
    "build_poker_legends_number_ocr_report",
    "parse_poker_legends_chip_amount",
    "parse_poker_legends_chip_components",
    "parse_poker_legends_chip_numbers",
    "build_poker_legends_screen_scan",
    "build_poker_legends_session_timeline",
    "build_poker_legends_truth_overlay",
    "compare_llm_candidate_to_roi",
    "draw_layout_overlay",
    "detect_poker_legends_screen_state",
    "detect_poker_legends_screen_state_from_image",
    "evaluate_fixture",
    "evaluate_poker_legends_card_classifier",
    "evaluate_poker_legends_card_consensus",
    "evaluate_poker_legends_card_consensus_suite",
    "evaluate_poker_legends_card_part_templates",
    "evaluate_poker_legends_card_templates",
    "evaluate_poker_legends_button_templates",
    "evaluate_poker_legends_screen_state",
    "evaluate_recognition",
    "execute_llm_annotation_package",
    "ingest_video",
    "merge_poker_legends_truth",
    "materialize_poker_legends_template_dataset",
    "poker_legends_layout_regions",
    "recognize_from_annotation",
    "score_to_dict",
    "screen_state_from_poker_legends_annotation",
    "scan_poker_legends_ingest",
    "select_keyframes",
    "select_poker_legends_card_review_candidates",
]
